services:
  traefil:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8080:8080

  web:
    image: "ghcr.io/victorfer1/cesi_cicd/"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: info
      ACCEPT_EULA: "Y"
    volumes:
      - ./docker/db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8081:8080