name: build-tests-actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Run end-to-end tests
        run: npm run e2e:headless

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: e2e-video
          path: cypress/videos/

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "\
          cd cesi-cicd && \
          git pull && \
          npm install && \
          npm run build && \
          pm2 start npm -- start"

  package:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
      - name: Docker Login
        run: docker login ghcr.io -u victorfer1 -p ${{ secrets.ACCESS_TOKEN }}
      - name: Docker Build
        run: docker build -t ghcr.io/victorfer1/cesi-cicd/web:latest .
      - name: Docker Push
        run: docker push ghcr.io/victorfer1/cesi-cicd/web:latest
