name: build-actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "18"
      - run: npm install
      - run: npm run build
      - run: ls -lah
      - run: npm run e2e:headless
