name: build-tests-actions
run-name: ${{ github.actor }} SSH Connect
on: [push]

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "ls"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd cesi-cicd && git pull && npm install && npm run build && pm2 start npm -- start"

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:
  #         path: |
  #           node_modules
  #           /home/runner/.cache/cypress
  #          key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
  #     - run: npm install
  #     - run: npm run build

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #     with:
  #       path: |
  #         node_modules
  #         /home/runner/.cache/cypress
  #       key: ${{ runner.os }}-node-${{ hashFiles('/package-lock.json') }}
  #     - run: npm run e2e:headless
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: e2e-video
  #         path: cypress/videos/
